Apply suggestions from code review by edupont
Co-Authored-By: edupont <emeric.dupont@agol.org>

diff --git a/tools/exportNotebook b/tools/exportNotebook
--- a/tools/exportNotebook
+++ b/tools/exportNotebook
@@ -142,7 +142,7 @@ else
     rM2svg_cmd="rM2svg"
 fi
 
-[ ! -z $COLOR_ANNOTATIONS ] && rM2svg_cmd="$rM2svg_cmd -c"
+[ -n $COLOR_ANNOTATIONS ] && rM2svg_cmd="$rM2svg_cmd -c"
 
 tmpfolder=$(mktemp -d)
 echo "Using temp folder '$tmpfolder'"
@@ -150,7 +150,7 @@ echo "Using temp folder '$tmpfolder'"
 OUTPUT_UUID=""
 
 if [ -f "$path" ]; then
-    tar -xvzf "$path" -C "$tmpfolder"
+    tar -xvzf "$path" -C "$tmpfolder" || exit 1
     filename="$(basename $path .tar.gz)"
 
 else
@@ -172,7 +172,7 @@ else
 
     # Entry not found
     if [ "${#DOCUMENTS_UUIDS[@]}" -eq 0 ]; then
-        echo "repull: Unable to find document: $path"
+        echo "exportNotebook: Unable to find document: $path"
         exit_failed
     fi
 
@@ -327,7 +327,7 @@ done
 if command -v "svgo" > /dev/null; then
     for f in "${tmpfolder}"/foreground*.svg; do
         svgo -i "$f"
-        [ ! $? -eq 0 ] && echo "Failed to optimize svg '$f'" && exit 1
+        [ ! $? -eq 0 ] && echo "Failed to optimize svg '$f'" && continue
     done
 fi
 
@@ -361,15 +361,15 @@ else
     echo "Left temporary dir '${tmpfolder}'"
 fi
 
-if [ ! -z $ASK_RENAME ]; then
+if [ -n $ASK_RENAME ]; then
     xdg-open "${filename}.pdf"
-    [ ! -z "$OUTPUT_UUID" ] && echo "Last modified: ${DOCUMENTS_DATES[$OUTPUT_UUID]}"
+    [ -n "$OUTPUT_UUID" ] && echo "Last modified: ${DOCUMENTS_DATES[$OUTPUT_UUID]}"
     echo
     read -rp "New name w/o extension, or press Enter to delete files: " NEWFILENAME
     echo
-    if [ ! -z "$NEWFILENAME" ]; then
-        mv -v "${filename}.pdf" "${NEWFILENAME}.pdf"
-        mv -v "${filename}.tar.gz" "${NEWFILENAME}.tar.gz"
+    if [ -n "$NEWFILENAME" ]; then
+        mv -vi "${filename}.pdf" "${NEWFILENAME}.pdf"
+        mv -vi "${filename}.tar.gz" "${NEWFILENAME}.tar.gz"
         filename="${NEWFILENAME}"
     else
         rm -v "${filename}.pdf" "${filename}.tar.gz"
