Make exportNotebook work with new reMarkable versions plus other features (#29)
* 'exportNotebook expects -r IPADDR argument first, support filenames with spaces'

* try inkscape

* optimize svgs and conversion to pdf

* working version of exportNotebook

* fix hardcoded path

* add options, fix potential wrong naming

* add empty pages when rm file is missing, add minor fixes

* add rm2svg credits

* improve askrename prompt

* Apply suggestions from code review by edupont

Co-Authored-By: edupont <emeric.dupont@agol.org>

* fix test -n checks, change rename prompt, add msg on
invalid tar.gz

* support .lines v3 and v5, change timeout and clarify
rename prompt

diff --git a/tools/exportNotebook b/tools/exportNotebook
--- a/tools/exportNotebook
+++ b/tools/exportNotebook
@@ -7,65 +7,258 @@
 # - rsvg-convert (optional, to avoid rasterizing of lines)
 # - gs & pdfinfo (optional, to account for original pdf size)
 
-if [[ $# -eq 0 ]] ; then
-    echo "Usage: ./exportNotebook (Partial)NotebookName AdditionalrM2svgArguments"
-    echo "You can additionally append the -c argument for coloured annotations."
-    exit 0
+
+ASK_RENAME=""
+COLOR_ANNOTATIONS=""
+SSH_HOST="10.11.99.1"
+SSH_TIMEOUT=1
+path=""
+STROKE_WIDTH="3"
+OPACITY="1"
+bad_args=""
+arg_num=0
+KEEP_TEMPDIR=""
+
+while [[ $# -gt 0 ]]; do
+    key="$1"
+    case $key in
+        -n|--askrename)
+            ASK_RENAME=true
+            shift
+            ;;
+        -c|--coloured_annotations)
+            COLOR_ANNOTATIONS=true
+            shift
+            ;;
+        -k|--keep_tempdir)
+            KEEP_TEMPDIR=true
+            shift
+            ;;
+        -r|--remoteip)
+            SSH_HOST="$2"
+            SSH_TIMEOUT=10
+            shift
+            shift
+            ;;
+        -w|--strokewidth)
+            STROKE_WIDTH="$2"
+            shift
+            shift
+            ;;
+        -o|--opacity)
+            OPACITY="$2"
+            shift
+            shift
+            ;;
+        -*)
+            echo "Unknown option: $1"
+            bad_args=TRUE
+            shift
+            ;;
+        *)
+            arg_num=$(( $arg_num + 1 ))
+            case $arg_num in
+                1)
+                    path="$1"
+                    shift
+                    ;;
+                *)
+                    bad_args=TRUE
+            esac
+            ;;
+    esac
+done
+
+if [[ $bad_args == TRUE || $arg_num < 1 ]]; then
+    echo "Usage: $(basename "$0") [--askrename|-n] [--remoteip|-r STR] [--strokewidth|-w INT] [--opacity|-o FLOAT] [--coloured_annotations|-c] [--keep_tempdir|-k] <document-name-match|tar.gz-file>"
+    exit 1
 fi
+
+
+function rmtgrep {
+    RET_MATCH="$(${SSH_CMD} "$SSH_REMOTE" "/bin/egrep -$1 '$2' $3")"
+    echo "/bin/egrep -$1 '$2' $3: $RET_MATCH"
+}
+
+declare -A DOCUMENTS_NAMES
+declare -A DOCUMENTS_DATES
+
+function find_document {
+    OLD_IFS=$IFS
+    IFS='/' _PATH=(${2#/}) # Sort path into array
+    IFS=$OLD_IFS
+
+    MATCH="${_PATH[$3]}"
+    [ ${MATCH: -1} == "$" ] && MATCH="${MATCH:0:-1}" || MATCH="${MATCH}.*"
+    [ ${MATCH:0:1} == "^" ] && MATCH="${MATCH:1}" || MATCH=".*${MATCH}"
+    rmtgrep "ile" "\"visibleName\": \"${MATCH}\"" "/home/root/.local/share/remarkable/xochitl/*.metadata"
+    echo $RET_MATCH
+    matches_by_name="$RET_MATCH"
+
+    for metadata_path in $matches_by_name; do
+
+        metadata="$(${SSH_CMD} "$SSH_REMOTE" "cat $metadata_path")"
+
+        if ! echo "$metadata" | grep -qF "\"parent\": \"$1\""; then
+            continue
+        fi
+
+        if echo "$metadata" | grep -qF '"deleted": true'; then
+            continue
+        fi
+
+        if [[ "$(expr $3 + 1)" -eq "${#_PATH[@]}" ]]; then
+            if echo "$metadata" | grep -qF '"type": "DocumentType"'; then
+                _UUID="$(basename "$metadata_path" .metadata)"
+                NAME="$(echo "$metadata" | grep '"visibleName"' | sed 's/^.*: \+"\([^"]\+\)"/\1/g')"
+                IDATE="$(echo "$metadata" | grep '"lastModified"' | egrep -o '[0-9]*')"
+                STRDATE="$(date -d @$(expr ${IDATE} / 1000) '+%Y-%m-%d %H:%M:%S')"
+                DOCUMENTS_NAMES["$_UUID"]="$NAME"
+                DOCUMENTS_DATES["$_UUID"]="$STRDATE"
+            fi
+        else
+            if echo "$metadata" | grep -qF '"type": "CollectionType"'; then
+                find_document "$(basename "$metadata_path" .metadata)" "$2" "$(expr $3 + 1)"
+            fi
+        fi
+
+    done
+}
+
+# Kills SSH session and exits with return 1
+function exit_failed {
+    ${SSH_CMD} -O exit "$SSH_REMOTE"
+    exit 1
+}
+
 
 # Make sure we have rM2svg
 command -v rM2svg >/dev/null 2>&1
 if [[ $? -ne 0 ]]; then
-    if [[ -x rM2svg ]]; then
-        rM2svg_cmd="$(dirname `readlink -f $0`)/rM2svg"
-    else
-        print "Cannot find rM2svg"
+    rM2svg_cmd="$(dirname `readlink -f $0`)/rM2svg"
+    if [ ! -x "$rM2svg_cmd" ]; then
+        echo "Cannot find rM2svg"
         exit 1
     fi
 else
     rM2svg_cmd="rM2svg"
 fi
 
-# Check if ssh configuration for "remarkable" exists
-grep -Fxq "host remarkable" ~/.ssh/config
-if [ $? -eq 0 ]; then
-    SSH_IP="root@remarkable"
-else
-    SSH_IP="root@10.11.99.1"
-fi
-
-# Start SSH in ControlMaster mode
-control_path_dir=$(mktemp -d --suffix=ssh_remark)
-control_options="-o ControlPath=$control_path_dir/%h_%p_%r -o ControlPersist=10s"
-ssh -M ${control_options} ${SSH_IP} exit
-
-# Getting the notebook prefix (Newest notebook matching the name)
-id=$(ssh ${control_options} ${SSH_IP} "ls -rt .local/share/remarkable/xochitl/*.metadata | xargs fgrep -l $1" | tail -n1 | cut -d. -f1,2)
-
-test -z "$id" && exit 1
+[ -n "$COLOR_ANNOTATIONS" ] && rM2svg_cmd="$rM2svg_cmd -c"
 
 tmpfolder=$(mktemp -d)
+echo "Using temp folder '$tmpfolder'"
 
-# Getting notebook data
-scp $control_options -q ${SSH_IP}:"${id}".{lines,pagedata,metadata} "${tmpfolder}"/
+OUTPUT_UUID=""
 
-# Copy underyling document pdf if it exists
-ssh $control_options -q ${SSH_IP} "[[ -f "${id}.pdf" ]]" && scp $control_options -q ${SSH_IP}:"${id}.pdf" "${tmpfolder}"
+if [ -f "$path" ]; then
+    tar -xvzf "$path" -C "$tmpfolder"
+    [ ! $? -eq 0 ] && echo "File '$path' exists, but it is not a valid .tar.gz" && exit 1
+    filename="$(basename $path .tar.gz)"
+
+else
+
+    # Establish remote connection
+    SSH_REMOTE="root@${SSH_HOST}"
+    SSH_CMD="ssh -S remarkable-ssh"
+    SCP_CMD="scp -o ControlPath=remarkable-ssh"
+    ${SSH_CMD} -o ConnectTimeout=${SSH_TIMEOUT} -M -f -q ${SSH_REMOTE} -N
+    [ ! $? -eq 0 ] && echo "Failed to establish connection with the device!" && exit 1
+
+    # Search for given pattern
+    echo "Searching for '$path'"
+    find_document "" "$path" 0
+
+    DOCUMENTS_UUIDS=(${!DOCUMENTS_NAMES[@]})
+    echo "${#DOCUMENTS_UUIDS[@]}"
+    echo "${DOCUMENTS_UUIDS[@]}"
+
+    # Entry not found
+    if [ "${#DOCUMENTS_UUIDS[@]}" -eq 0 ]; then
+        echo "exportNotebook: Unable to find document: $path"
+        exit_failed
+    fi
+
+    # Multiple entries match
+    if [ "${#DOCUMENTS_UUIDS[@]}" -gt 1 ]; then
+        echo "'$path' matches multiple files!"
+
+        while true; do
+            echo
+
+            # Display file id's from most recently modified to oldest
+            for (( i=0; i<${#DOCUMENTS_UUIDS[@]}; i++ )); do
+                _UUID=${DOCUMENTS_UUIDS[$i]}
+                NAME=${DOCUMENTS_NAMES[$_UUID]}
+                STRDATE=${DOCUMENTS_DATES[$_UUID]}
+                echo -e "$(expr $i + 1). - $_UUID - $NAME - $STRDATE"
+            done
+
+            echo
+            read -rp "Select your target: " INPUT
+            echo
+
+            if [[ "$INPUT" -gt 0  && "$INPUT" -lt $(expr $i + 1) ]]; then
+                let INPUT=INPUT-1
+                OUTPUT_UUID="${DOCUMENTS_UUIDS[$INPUT]}"
+                break
+            fi
+
+            echo "Invalid input"
+        done
+
+
+        # Entry found
+    else
+        OUTPUT_UUID="$DOCUMENTS_UUIDS"
+    fi
+
+    echo "UUID : $OUTPUT_UUID"
+    echo "Name : ${DOCUMENTS_NAMES[$OUTPUT_UUID]}"
+
+
+    UUID_PATH="/home/root/.local/share/remarkable/xochitl/${OUTPUT_UUID}"
+    # Getting notebook data
+    ${SCP_CMD} -rp ${SSH_REMOTE}:"$UUID_PATH"{,.content,.pagedata,.metadata} "${tmpfolder}"/
+    [ ! $? -eq 0 ] && echo "Failed to get notebook data" && exit 1
+
+    # Copy underyling document pdf if it exists
+    ${SSH_CMD} ${SSH_REMOTE} "[[ -f "${UUID_PATH}.pdf" ]]"
+    if [ $? -eq 0 ]; then
+        ${SCP_CMD} ${SSH_REMOTE}:"${UUID_PATH}.pdf" "${tmpfolder}"
+        [ ! $? -eq 0 ] && echo "Failed to get underlying pdf document" && exit 1
+    fi
+
+    if [ ! -f "${tmpfolder}"/*.pdf ]; then
+        # Getting template files
+        sort -u "${tmpfolder}"/*.pagedata | while read -r tpl; do
+            ${SCP_CMD} -T ${SSH_REMOTE}:"'/usr/share/remarkable/templates/${tpl}.png'" "${tmpfolder}"/
+            [ ! $? -eq 0 ] && echo "Failed to download template file '${tpl}'" && exit 1
+        done
+    fi
+
+    filename="${DOCUMENTS_NAMES[$OUTPUT_UUID]}"
+    # Strip .pdf suffix if it already exists (document vs. notebook)
+    filename=$(basename -s .pdf "${filename//\"/}")
+
+    tar cvzf "${filename}.tar.gz" -C "${tmpfolder}" .
+
+    ${SSH_CMD} -O exit ${SSH_REMOTE}
+
+fi
 
 # Fix for single page notebooks with no template (empty pagedata file by default)
-if [ ! -s "${tmpfolder}"/*.pagedata ]
-then
+if [ ! -s "${tmpfolder}"/*.pagedata ]; then
   echo "Blank" > "${tmpfolder}"/*.pagedata
 fi
 
 # Fix empty lines in pagedata files
 sed -i -e "s/^[[:blank:]]*$/Blank/" "${tmpfolder}"/*.pagedata
 
-filename=$(grep -F  '"visibleName"' "${tmpfolder}"/*.metadata | cut -d: -f2- | grep -o '"[^"]*"')
-echo "Exporting notebook ${filename} ($(wc -l "${tmpfolder}"/*.pagedata | cut -d\  -f1) pages)"
+NPAGES="$(wc -l "${tmpfolder}"/*.pagedata | cut -d\  -f1)"
+echo "Exporting '${filename}' (${NPAGES} pages)"
 
-if [ -f "${tmpfolder}"/*.pdf ]
-then
+if [ -f "${tmpfolder}"/*.pdf ]; then
     ln -s "${tmpfolder}/"*.pdf "${tmpfolder}/background_original.pdf"
     echo "Found underlying document PDF, using as background."
 
@@ -93,33 +286,96 @@ then
         ln -s ${tmpfolder}/background_original.pdf ${tmpfolder}/background.pdf
     fi
 else
-    # Getting template files
-    sort -u "${tmpfolder}"/*.pagedata | while read -r tpl; do
-    scp $control_options -q ${SSH_IP}:"'/usr/share/remarkable/templates/${tpl}.png'" "${tmpfolder}"/
-    done
 
     # Generate a PDF file out of the templates
     sed -e "s|^|\"${tmpfolder}\"/\"|" -e 's|$|.png"|' "${tmpfolder}"/*.pagedata | tr '\n' ' ' | sed -e "s|$|-transparent white \"${tmpfolder}\"/background.pdf|" | xargs convert
+    [ ! $? -eq 0 ] && echo "Failed to generate a PDF file out of the templates" && exit 1
 fi
 
 # Extract annotations and create a PDF
-$rM2svg_cmd --input "${tmpfolder}"/*.lines --output "${tmpfolder}/foreground" $2
+IPAGE=0
+jq '.pages' "${tmpfolder}"/*.content | jq '.[]' | while read -r page; do
+    SPAGE="${page:1:${#page}-2}"
+    let IPAGE=IPAGE+1
+    if [ -f "${tmpfolder}"/*/"${SPAGE}.rm" ]; then
+        echo "Processing page $IPAGE ($SPAGE)"
+        $rM2svg_cmd --input "${tmpfolder}"/*/"${SPAGE}.rm" --output "${tmpfolder}/foreground$(printf %03d $IPAGE).svg"
+        [ ! $? -eq 0 ] && echo "Failed to generate '${tmpfolder}/foreground$(printf %03d $IPAGE).svg'" && exit 1
+    else
+        echo "Generating empty page $IPAGE ($SPAGE)"
+cat << 'EOF' > "${tmpfolder}/foreground$(printf %03d $IPAGE).svg"
+<svg xmlns="http://www.w3.org/2000/svg" height="1872" width="1404">
+        <script type="application/ecmascript"> <![CDATA[
+            var visiblePage = 'p1';
+            function goToPage(page) {
+                document.getElementById(visiblePage).setAttribute('style', 'display: none');
+                document.getElementById(page).setAttribute('style', 'display: inline');
+                visiblePage = page;
+            }
+        ]]> </script>
+    <g id="p1" style="display:inline">
+<rect x="0" y="0" width="1404" height="1872" fill-opacity="0"/></g></svg>
+EOF
+    fi
+done
 
-if command -v "rsvg-convert" > /dev/null
-then
-    rsvg-convert -a -f pdf "${tmpfolder}"/foreground*.svg -o "${tmpfolder}"/foreground.pdf
-else
-    convert -density 100 "${tmpfolder}"/foreground*.svg -transparent white "${tmpfolder}"/foreground.pdf
+# Preprocess foreground*.svg
+for f in "${tmpfolder}"/foreground*.svg; do
+    # debug
+    #cp -v "$f" ~/debug/"$(basename "$f")" 
+    sed -i "s/stroke-width\:[\.0-9]\+/stroke-width:${STROKE_WIDTH}/g;s/opacity\:[\.0-9]\+/opacity:${OPACITY}/g" "$f"
+    [ ! $? -eq 0 ] && echo "Failed to reset stroke-width and opacity in '$f'" && exit 1
+done
+# - optimize svg with svgo
+if command -v "svgo" > /dev/null; then
+    for f in "${tmpfolder}"/foreground*.svg; do
+        svgo -i "$f"
+        [ ! $? -eq 0 ] && echo "Failed to optimize svg '$f'" && continue
+    done
 fi
 
-# Strip .pdf suffix if it already exists (document vs. notebook)
-filename=$(basename -s .pdf ${filename//\"/})
+# Convert svg to pdf
+if command -v "inkscape" > /dev/null; then
+    for f in "${tmpfolder}"/foreground*.svg; do
+        inkscape "$f" -d 200 --export-pdf="${f%.svg}.pdf"
+        [ ! $? -eq 0 ] && echo "Failed to convert to pdf via inkscape '$f'" && exit 1
+    done
+    pdftk "${tmpfolder}"/foreground*.pdf cat output "${tmpfolder}"/foreground.pdf
+    [ ! $? -eq 0 ] && echo "Failed to merge inkscape pdfs" && exit 1
+elif command -v "rsvg-convert" > /dev/null; then
+    rsvg-convert -a -f pdf "${tmpfolder}"/foreground*.svg -o "${tmpfolder}"/foreground.pdf
+    [ ! $? -eq 0 ] && echo "Failed to convert to pdf via rsvg-convert" && exit 1
+else
+    convert -density 100 "${tmpfolder}"/foreground*.svg -transparent white "${tmpfolder}"/foreground.pdf
+    [ ! $? -eq 0 ] && echo "Failed to convert to pdf via convert" && exit 1
+fi
 
 # Use multistamp instead of multibackground to preserve transparency
 pdftk "${tmpfolder}"/background.pdf multistamp "${tmpfolder}"/foreground.pdf output "${filename}.pdf"
+[ ! $? -eq 0 ] && echo "Failed to merge background and foreground pdfs" && exit 1
 
 filesize=$(ls -la "${filename}.pdf" | awk '{print $5}' | numfmt --to=iec-i --suffix=B --format="%.3f")
+
 echo "Written ${filesize} to ${filename}.pdf"
 
-ssh $control_options -O exit ${SSH_IP}
-rm -Rf "${tmpfolder}" "${control_path_dir}"
+if [ -z $KEEP_TEMPDIR ]; then
+    rm -Rf "${tmpfolder}"
+else
+    echo "Left temporary dir '${tmpfolder}'"
+fi
+
+if [ -n "$ASK_RENAME" ]; then
+    xdg-open "${filename}.pdf"
+    [ -n "$OUTPUT_UUID" ] && echo "Last modified: ${DOCUMENTS_DATES[$OUTPUT_UUID]}"
+    echo
+    read -rp "New name w/o extension, '!rm' to delete '${filename}.{pdf,tar.gz}', Enter to skip: " NEWFILENAME
+    echo
+    if [ -n "$NEWFILENAME" ]; then
+        if [ "$NEWFILENAME" == "!rm" ]; then
+            rm -v "${filename}.pdf" "${filename}.tar.gz"
+        else
+            mv -vi "${filename}.pdf" "${NEWFILENAME}.pdf"
+            mv -vi "${filename}.tar.gz" "${NEWFILENAME}.tar.gz"
+        fi
+    fi
+fi
