try inkscape

diff --git a/tools/exportNotebook b/tools/exportNotebook
--- a/tools/exportNotebook
+++ b/tools/exportNotebook
@@ -16,10 +16,9 @@ fi
 # Make sure we have rM2svg
 command -v rM2svg >/dev/null 2>&1
 if [[ $? -ne 0 ]]; then
-    if [[ -x rM2svg ]]; then
-        rM2svg_cmd="$(dirname `readlink -f $0`)/rM2svg"
-    else
-        print "Cannot find rM2svg"
+    rM2svg_cmd="$(dirname `readlink -f $0`)/rM2svg"
+    if [[ ! -x ${rM2svg_cmd} ]]; then
+        echo "Cannot find rM2svg"
         exit 1
     fi
 else
@@ -33,22 +32,32 @@ SSH_IP="root@$1"
 shift
 
 # Start SSH in ControlMaster mode
-control_path_dir=$(mktemp -d --suffix=ssh_remark)
-control_options="-o ControlPath=$control_path_dir/%h_%p_%r -o ControlPersist=10s"
-ssh -M ${control_options} ${SSH_IP} exit
+ssh_cmd="ssh -o ControlPersist=10s"
+scp_cmd=scp
+rm_tmpfolders="rm -Rf \"${tmpfolder}\""
+
+grep ControlPath ~/.ssh/config >/dev/null
+if [ ! $? -eq 0 ]; then
+    control_path_dir=$(mktemp -d --suffix=ssh_remark)
+    control_options="-o ControlPath=$control_path_dir/%h_%p_%r"
+    rm_tmpfolders="${rm_tmpfolders} \"${control_path_dir}\""
+    ssh_cmd="${ssh_cmd} ${control_options}"
+    scp_cmd="${scp_cmd} ${control_options}"    
+fi
+${ssh_cmd} ${SSH_IP} exit
 
 # Getting the notebook prefix (Newest notebook matching the name)
-id=$(ssh ${control_options} ${SSH_IP} "ls -rt .local/share/remarkable/xochitl/*.metadata | xargs fgrep -l $1" | tail -n1 | cut -d. -f1,2)
+id=$(${ssh_cmd} -M ${SSH_IP} "ls -rt .local/share/remarkable/xochitl/*.metadata | xargs fgrep -l $1" | tail -n1 | cut -d. -f1,2)
 
 test -z "$id" && exit 1
 
 tmpfolder=$(mktemp -d)
 
 # Getting notebook data
-scp $control_options -q ${SSH_IP}:"${id}".{lines,pagedata,metadata} "${tmpfolder}"/
+${scp_cmd} -q ${SSH_IP}:"${id}".{lines,pagedata,metadata} "${tmpfolder}"/
 
 # Copy underyling document pdf if it exists
-ssh $control_options -q ${SSH_IP} "[[ -f "${id}.pdf" ]]" && scp $control_options -q ${SSH_IP}:"${id}.pdf" "${tmpfolder}"
+${ssh_cmd} -q ${SSH_IP} "[[ -f "${id}.pdf" ]]" && ${scp_cmd} -q ${SSH_IP}:"${id}.pdf" "${tmpfolder}"
 
 # Fix for single page notebooks with no template (empty pagedata file by default)
 if [ ! -s "${tmpfolder}"/*.pagedata ]
@@ -93,7 +102,7 @@ then
 else
     # Getting template files
     sort -u "${tmpfolder}"/*.pagedata | while read -r tpl; do
-    scp $control_options -q ${SSH_IP}:"'/usr/share/remarkable/templates/${tpl}.png'" "${tmpfolder}"/
+    ${scp_cmd} -q ${SSH_IP}:"'/usr/share/remarkable/templates/${tpl}.png'" "${tmpfolder}"/
     done
 
     # Generate a PDF file out of the templates
@@ -103,8 +112,10 @@ fi
 # Extract annotations and create a PDF
 $rM2svg_cmd --input "${tmpfolder}"/*.lines --output "${tmpfolder}/foreground" $2
 
-if command -v "rsvg-convert" > /dev/null
-then
+
+if command -v "inkscape" > /dev/null; then
+    inkscape "${tmpfolder}"/foreground*.svg --export-pdf="${tmpfolder}"/foreground.pdf
+elif command -v "rsvg-convert" > /dev/null; then
     rsvg-convert -a -f pdf "${tmpfolder}"/foreground*.svg -o "${tmpfolder}"/foreground.pdf
 else
     convert -density 100 "${tmpfolder}"/foreground*.svg -transparent white "${tmpfolder}"/foreground.pdf
@@ -119,5 +130,5 @@ pdftk "${tmpfolder}"/background.pdf multistamp "${tmpfolder}"/foreground.pdf out
 filesize=$(ls -la "${filename}.pdf" | awk '{print $5}' | numfmt --to=iec-i --suffix=B --format="%.3f")
 echo "Written ${filesize} to ${filename}.pdf"
 
-ssh $control_options -O exit ${SSH_IP}
-rm -Rf "${tmpfolder}" "${control_path_dir}"
+${ssh_cmd} -O exit ${SSH_IP}
+${rm_tmpfolders}
